Hunterise with protobuf and pybind11 packages
hunter-packages/onnx pull request #1
Opened 2019-03-12 07:28 UTC by xsacha

2019-03-12 07:30 UTC, xsacha commented
Test still fails with

-- Configuring done
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "test" links to target "protobuf::libprotobuf" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

2019-03-12 08:26 UTC, ruslo requested changes
Please split changes

2019-03-12 08:26 UTC, ruslo commented on CMakeLists.txt
> +include(cmake/Hunter/HunterGate.cmake)
I don't see this module committed.

2019-03-12 08:26 UTC, ruslo commented on CMakeLists.txt
> +  EXPORT ONNXTargets
Try to keep change minimal. There is no need to modify this line.

2019-03-12 08:26 UTC, ruslo commented on CMakeLists.txt
> +        ${pybind11_INCLUDE_DIRS})
We are not entering the `else` block, you can keep the code to minimize number of changes in patch.

2019-03-13 03:15 UTC, xsacha commented
Ready to go

2019-03-15 14:39 UTC, ruslo approved these changes

2019-03-15 14:40 UTC, merged

2019-03-15 14:40 UTC, ruslo commented
Released: https://github.com/hunter-packages/onnx/releases/tag/v1.4.1-p0